name: focal_point
description: A new Job-Search application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.2+3
  geolocator: ^5.3.1
  gscarousel: ^0.0.1
  android_intent: ^0.3.7+7
  shared_preferences: ^0.5.12+4
  carousel_pro: ^1.0.0
  http: ^0.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: CustomIconFont
      fonts:
        - asset: assets/fonts/CustomIconFont.ttf
    - family: googlesansmed
      fonts:
        - asset: assets/fonts/googlesansmedium.ttf
    - family: googlesansreg
      fonts:
        - asset: assets/fonts/googlesansregular.ttf
